### ISSUE TITLE
An error occured while installing ep_table_of_contents

### ISSUE THREAD

**Issue by Michael2222** [JohnMcLear/ep_table_of_contents#20]
Greetings,
I have by the installation an error:

An error occured while installing ep_table_of_contents
shasum check failed for /Root/tmp/npm-7991-........./tmp.tgz
Expected: f76 .............................
Actual: f8e0..............................
From: https://registry.npmjs.org/ep_table_of_contents/-/ep_table_of_contents-0.1.2.tgz

Have you an idea?
Regards
   Michael

**Comment by JohnMcLear** [comment]
99% user error, plugin is fine.
