### ISSUE TITLE
ReferenceError: Can't find variable: exports

### ISSUE THREAD

**Issue by jhamfler** [JohnMcLear/ep_table_of_contents#29]
After updating to 0.1.14 I am receiving the following error whenever I enter a pad (though it's still loading)

```
An error occurred while loading the pad
ReferenceError: Can't find variable: exports in
https://pad.url.net/static/plugins/ep_table_of_contents/static/js/toc.js (line 162)
```

**Comment by JohnMcLear** [comment]
Try restart your instance

**Comment by skupfer** [comment]
Doesn't fix the error for me. Restarted several times now... Nothing I can see in the error log, just the one above while loading the page

**Comment by NAHNAH55** [comment]
I also have this same problem. The only thing that fixes it for me is removing the code after line 162 in toc.js, which breaks the auto-update function.
